# Generated by Django 2.0 on 2020-05-19 13:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Not Specified', max_length=32)),
                ('is_enabled', models.BooleanField(default=False)),
                ('logging', models.BooleanField(default=False)),
                ('email_notification', models.BooleanField(default=False)),
                ('crowd_threshold', models.IntegerField(default=20)),
                ('position', models.CharField(default='Not Specified', max_length=64)),
                ('output_width', models.IntegerField(default=720)),
                ('output_height', models.IntegerField(default=480)),
                ('output_depth', models.IntegerField(choices=[(1, 'GRAY'), (3, 'RGB')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='EmailSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_email', models.EmailField(default='notifyme@example.com', max_length=254)),
                ('smtp_server', models.CharField(default='smtp.gmail.com', max_length=32)),
                ('server_port', models.IntegerField(default=587)),
                ('login', models.EmailField(default='login@example.com', max_length=254)),
                ('password', models.CharField(default='login_password', max_length=32)),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('event_type', models.CharField(max_length=32)),
                ('event_name', models.CharField(max_length=32)),
                ('count', models.IntegerField(default=0)),
                ('media_type', models.CharField(default='image', max_length=32)),
                ('media_path', models.CharField(default='/media', max_length=64)),
                ('heatmap', models.CharField(default='/media', max_length=64)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.Camera')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_framerate', models.IntegerField(default=20)),
                ('db_event_lifetime', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language', models.CharField(default='English', max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=32)),
                ('model_framework', models.CharField(max_length=32)),
                ('date_added', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('in_batchsize', models.IntegerField(default=1)),
                ('in_height', models.IntegerField(default=0)),
                ('in_width', models.IntegerField(default=0)),
                ('in_depth', models.IntegerField(choices=[(1, 'GRAY'), (3, 'RGB')], default=1)),
                ('out_batchsize', models.IntegerField(default=1)),
                ('out_height', models.IntegerField(default=0)),
                ('out_width', models.IntegerField(default=0)),
                ('out_depth', models.IntegerField(choices=[(1, 'GRAY'), (3, 'RGB')], default=1)),
                ('shape_order', models.CharField(choices=[('bdhw', 'batch_size, depth, height, width'), ('bdwh', 'batch_size, depth, width, height'), ('bhwd', 'batch_size, height, width, depth'), ('bhdw', 'batch_size, height, depth, width'), ('bwdh', 'batch_size, width, depth, height'), ('bwhd', 'batch_size, width, height, depth'), ('wbhd', 'width, batch_size, height, depth'), ('wbdh', 'width, batch_size, depth, height'), ('whdb', 'width, height, depth, batch_size'), ('whbd', 'width, height, batch_size, depth'), ('wdbh', 'width, depth, batch_size, height'), ('wdhb', 'width, depth, height, batch_size'), ('hdwb', 'height, depth, width, batch_size'), ('hdbw', 'height, depth, batch_size, width'), ('hwbd', 'height, width, batch_size, depth'), ('hwdb', 'height, width, depth, batch_size'), ('hbdw', 'height, batch_size, depth, width'), ('hbdw', 'height, batch_size, width, depth'), ('dbwh', 'depth, batch_size, width, height'), ('dbhw', 'depth, batch_size, height, width'), ('dwhb', 'depth, width, height, batch_size'), ('dwbh', 'depth, width, batch_size, height'), ('dhbw', 'depth, height, batch_size, width'), ('dhwb', 'depth, height, width, batch_size')], max_length=4)),
                ('is_converted', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Camera events disabled', max_length=64, unique=True)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ServerConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(choices=[('INFERENCE', 'Inference Server'), ('CONVERSION', 'Conversion Server')], max_length=16)),
                ('url', models.CharField(default='http://127.0.0.1', max_length=32)),
                ('port', models.IntegerField(default=8001)),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.Language'),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='camera',
            name='camera_usage_scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.Scenario'),
        ),
        migrations.AddField(
            model_name='camera',
            name='model_used',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.Model'),
        ),
        migrations.AddField(
            model_name='camera',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
